unique_ids:
  assets:
    standard-page.html: BVSYGNZ6Y4U64QR2IGL5OML2KS6CQ4BO
    theme.css: HHRJEVUHG3RP4HQWG6KHMOPIURHK45WP
  forms:
    Form1: UZWCHHS5AFP4XQ2OD4MIGUV6XPGCP6NQ
  modules: {}
  scripts: {}
  server_modules: {}
